### ISSUE TITLE
Posible error en ejercicio y petición de pycheck

### ISSUE THREAD

**Issue by josecox13** [sdelquin/aprendepython#33]
Hola! Lo primero quiero darte las gracias por tu pedazo de manual. Me está ayudando muchísimo. Soy nuevo en esto de la programación y menudo mundo tan interesante.
Creo que he detectado un errores, pero puede que esté equivocado. Te los dejo aquí para que les eches un ojo :)
En la sección 3.3 en el apartado "Longitud de cadena" en el ejemplo se usa len(proverb) y da 27. Creo que la longitud de 'Lo cortés no quita lo valiente' es 30. (Puede que 27 sea la longitud de 'Agua pasada no mueve molino')

Por otro lado no soy capaz de abrir los ejercicios con pycheck. No sé como instalarlo (estoy usando VisualStudio), creo que vendría bien una sección de como hacerlo. Mil gracias por tu labor.

**Comment by josecox13** [comment]
También en la sección Valor Nulo del capítulo 4, en el segundo código, la función print debería ser print('Value is clearly void') y pone None, entiendo que será un error tipográfico

**Comment by sdelquin** [comment]
Hola @josecox13. Te agradezco muchísimo tus aportaciones! Ya he corregido los dos typos: suelen ocurrir porque voy modificando y hago copiar-pegar, y se me quedan cosas atrás. Lo típico.

En cuanto a pycheck, cada ejercicio tiene un enlace a https://pycheck.es donde se explica cómo instalarlo y utilizarlo. Si te parece que aún así no está bien explicado, estoy abierto a sugerencias de cómo podría mejorarse.

Saludos cordiales.

Fixed with 507cd31
